### PR TITLE
version 0.1.0

### PR DESCRIPTION
**Pull request by kathrynkodama**
Signed-off-by: Kathryn Kodama <kathryn.s.kodama@gmail.com>

### CODE REVIEW

**Comment by kathrynkodama** [comment]
@mattbsox and @TrevCraw please review

**Comment by mattbsox** [comment]
The build failures are to be expected with the release versions.

**Comment by TrevCraw** [comment]
Do the POMs in the jakarta.eclipse projects also need to be updated?

**Comment by kathrynkodama** [comment]
> Do the POMs in the jakarta.eclipse packages also need to be updated?

We don't release `jakarta.eclipse`, but I guess for consistency we should update that version as well.

**Comment by TrevCraw** [comment]
Another line to update in org.eclipse.lsp4jakarta.lsp4e.core/pom.xml:

https://github.com/eclipse/lsp4jakarta/blob/8f130d888fa0e4dd6b8771121ab60563b7939b7c/jakarta.eclipse/org.eclipse.lsp4jakarta.lsp4e.core/pom.xml#L49

**Review by TrevCraw — APPROVED** [review]

**Pull request merged**
